FROM ubuntu:18.04

RUN  apt-get update && \
     apt-get -y upgrade && \
     apt-get install -qq  -y \
       acl \
       apt-utils \
       autoconf \
       automake \
       bash \
       binutils \
       build-essential \
       ccache \
       cmake \
       cpio \
       curl \
       g++ \
       gcc \
       gettext \
       git \
       sudo \
       x11-apps \
       xdg-utils \
       wget \
       zip \
       zlib1g-dev && \
     apt-get autoremove && apt-get autoclean

ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID -o xilinx
RUN useradd -m -u $UID -g $GID -o -s /bin/bash xilinx

RUN usermod -a -G sudo xilinx
RUN echo "xilinx ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


USER xilinx

ENV DISPLAY :0

CMD [ "/bin/bash"]

